name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: first script
        run: echo "this is pen"
      - name: pull
        uses: actions/checkout@v2
      - name: second script
        run: |
          ls -al
          cd .github/workflows/
          ls -al
          whoami